packages:
  - "packages/*"
allowBuilds:
  '@sentry/cli': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies:
  - "@sentry/cli"
  - esbuild
  - sharp
